---
title: "TobaccoConsumption"
author: "Jorge Aguilar Valenzuela"
date: '2022-05-13'
output: pdf_document
---
```{r}
library(tidyverse)
library(TTR)
library(forecast)

#1 - Database Tobacco Consumption
df = read.csv('TobaccoConsumptiondb.csv',as.is=TRUE, header = T)

view(df)

summary(df)
```

```{r}
#Correlation between variables in Scatterplot Graph
cor.test(df$Total,
         df$Total.Per.Capita)
```


```{r}
# Scatterplot Graph

ggplot(df, aes(x = Total, y = Total.Per.Capita, color = Measure)) + 
  geom_point()

```

```{r}
#Boxplot Graph

ggplot(df, aes(x = Measure, y = Total.Per.Capita)) +
  geom_boxplot() +
  theme_classic() +
  labs(title = "Box Plot") + 
  labs(subtitle = "Basic boxplot showing Measure for the total per capita")

```

```{r}
#Bar Plot Graph


ggplot(df, aes(x = Measure)) +
  geom_bar( fill = "#69b3a2",
                 color = "black",
                 alpha = 0.9) +
  ggtitle("Bar Plot") +
  theme_light() +
  theme(plot.title = element_text(size = 15))

```


```{r}
#Machine Learning
#Linear Regression

res.aov <- aov(Total.Per.Capita ~ Domestic, data=df) 
summary(res.aov)

res.aov <- aov(Total.Per.Capita ~ Population, data=df) 
summary(res.aov)

smp_size <- floor(0.8 * nrow(df))
train_ind <- sample(seq_len(nrow(df)), size = smp_size)

training_set = df[train_ind, ]
test_set = df[-train_ind, ]

linearmodel <- lm(Total.Per.Capita ~  Imports + Domestic , data=training_set)
summary(linearmodel)

test_set$prediction <- predict(linearmodel,newdata = test_set)

cor(test_set$Total.Per.Capita,test_set$prediction)
error <- test_set$Total.Per.Capita-test_set$prediction
hist(error)
mean(error)
```

```{r}
library(corrgram)
corrgram(df,upper.panel=panel.cor)

```

```{r}
#Time Series Model
#Creating a forecast to match the prediction based on the rolling Measure

df1 <- df %>% group_by(Year, Measure) %>% summarise(totalcigs = sum(Total), .groups = 'drop') %>% mutate(rolling = runMean(totalcigs, 2))

df1$rollingMeasure <-
  as.factor(ifelse(
    df1$Measure == 'All Combustibles',
    'R All Combustibles',
    ifelse(
      df1$Measure == 'Cigarettes',
      'R Cigarettes',
      ifelse(
        df1$Measure == 'Cigars',
        'R Cigars',
        ifelse(
          df1$Measure == 'Loose Tobacco',
          'R Loose Tobacco',
          ifelse(df1$Measure == 'Smokeless Tobacco', 'R Smokeless Tobacco', "a")
        )
      )
    )
  ))


ggplot(df1, aes(x = Year)) +
  geom_line(aes(y = totalcigs, colour = Measure)) +
  geom_line(aes(y = rolling, colour = rollingMeasure)) +
  theme_classic() +
  labs(title = "Time Series") +
  labs(subtitle = "Time Series showing Measure of totalcigs consumed in years ")

```


```{r}
#Time Series Prediction Based on Total per Capita in years


df2 <- df  %>% group_by(Year) %>% summarise(totalcigs = sum(Total.Per.Capita),
                                            .groups = 'drop')

# Rolling Mean used to calculate the simple moving average over the years
rollingmean <-
  function(x, n = 2) {
    stats::filter(x, rep(1 / n, n), sides = 2)
  }
totalcigars <- df2$totalcigs

# Rolling Mean used to calculate the simple moving average over the years
df2$rollingAverage <- rollingmean(totalcigars)

#Creating a forecast to match the prediction based on the rolling mean
df2$rollingAverage2 <-
  forecast::ma(totalcigars, order = 3, centre = TRUE)

#Timeseries Graph
ggplot(df2, aes(x = Year)) +
  geom_line(aes(y = totalcigs)) +
  geom_point(aes(y = totalcigs)) +
  geom_line(aes(y = rollingAverage), color = "darkblue") +
  geom_point(aes(y = rollingAverage))+
  theme_classic() +
  labs(title = "Time Series") +
  labs(subtitle = "Time Series showing the Total Per Capita of totalcigs consumed in years ")

```


